export enum MaterialType {
    RAFLATAC = "RAFLATAC",
        RAFLATAC_LAMINATED = "RAFLATAC_LAMINATED",
        RAFLATAC_PET = "RAFLATAC_PET",
        RITRAMA_LAMINATED = "RITRAMA_LAMINATED",
        RITRAMA_TRANSPARENT = "RITRAMA_TRANSPARENT",
}